export const series = [
  "Hocus Pocus",
  "Barbie",
  "Aladdin",
  "Prince of Persia",
  "Hugo",
  "Age of Empires",
  "Empire Earth",
  "Deus Ex",
  "Caesar",
  "Grandia",
  "Guilty Gear",
  "Fantasy Strike",
  "Metal Gear",
  "Dokapon",
  "Crazy Machines",
  "Quantum Conundrum",
  "Autobahn Raser",
  "Freespace",
  "Freelancer",
  "Toukiden",
  "Baten Kaitos",
  "Lost Odyssey",
  "Maiden & Spell",
  "Golden Sun",
  "Super Amazing Wagon Adventure",
  "Nanaca Crash",
  "Zangeki no Reginleiv",
  "Code R",
  "Avalon Code",
  "Another Code",
  "Hotel Dusk: Room 215",
  "No More Heroes",
  "Warriors of the Nile",
  "Gunfire Reborn",
  "Freedom Planet",
  "Monster Prom",
  "Shin Megami Tensei",
  "Graze Counter",
  "Katamari Damacy",
  "One Finger Death Punch",
  "Kung Fury",
  "Chemicus",
  "Moorhuhn",
  "Sven Bømwøllen",
  "My Time at Portia/Sandrock",
  "Slime Rancher",
  "Valkyrie Profile",
  "Valkyria Chronicles",
  "Towerfall",
  "Celeste",
  "Nidhogg",
  "Skullgirls",
  "Them's Fighting Herds",
  "Drunken Robot Pornography",
  "Earth Defense Force",
  "Keep Talking and Nobody Explodes",
  "Sanctum",
  "Risk of Rain",
  "Rocket League",
  "Gunpoint",
  "Cloudbuilt",
  "Dust: An Elysian Tail",
  "Jazz Jackrabbit",
  "Wacky Wheels",
  "Recettear",
  "Montaro",
  "Shantae",
  "Yoku's Island Express",
  "Zachtronics",
  "Desktop Dungeons",
  "Heroes of Might and Magic",
  "Bithell Games",
  "Buck Up and Drive",
  "Sudeki",
  "Distance",
  "Tanuki Sunset",
  "Before the Echo",
  "Spin Rhythm XD",
  "Just Shapes and Beats",
  "Chrono Ark",
  "Heat Signature",
  "Slipways",
  ".hack//",
  "Dept. Heaven",
  "Transistor",
  "Ether Vapor",
  "Sin & Punishment",
  "Trauma Center",
  "The Battle of Polytopia",
  "Advance Wars",
  "Kingdom",
  "Vampires Dawn",
  "Unterwegs in Düsterburg",
  "Mondschein",
  "I Was a Teenage Exocolonist",
  "Long Live the Queen",
  "Lost Phone",
  "DASH-DA-DASH DX",
  "Necrobarista",
  "VA-11 Hall-A",
]
